import React from 'react';
import { ExternalLink, CheckCircle, FileText, Recycle, Factory, Package, Battery, Zap } from 'lucide-react';

export default function Extendedproducer() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 via-blue-50 to-emerald-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b border-green-100">
        <div className="max-w-4xl mx-auto px-4 py-6">
          <div className="flex items-center gap-3">
            <Recycle className="w-8 h-8 text-green-600" />
            <h1 className="text-2xl font-bold text-gray-900">EPR Compliance India</h1>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-4xl mx-auto px-4 py-12">
        <article className="bg-white rounded-2xl shadow-lg p-8 md:p-12">
          {/* Title */}
          <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">
            Extended Producer Responsibility (EPR) in India
          </h1>
          <p className="text-xl text-gray-600 mb-8">A Complete Guide for Businesses</p>

          {/* Introduction */}
          <div className="prose prose-lg max-w-none mb-8">
            <p className="text-gray-700 leading-relaxed">
              Extended Producer Responsibility (EPR) in India is a regulatory framework that ensures producers, 
              importers, and brand owners take accountability for managing the waste generated by their products.
            </p>
            <p className="text-gray-700 leading-relaxed mt-4">
              In India, EPR is a legal obligation under various environmental regulations, particularly for 
              industries dealing with plastic waste, e-waste, batteries, and packaging materials. Companies that 
              fall under these categories must establish systems for waste collection, recycling, and responsible disposal.
            </p>
            <p className="text-gray-700 leading-relaxed mt-4">
              If your business manufactures or imports products with plastic packaging, electronics, or hazardous 
              waste, EPR compliance is mandatory under Indian law.
            </p>
          </div>

          {/* Quick Links */}
          <div className="bg-green-50 border border-green-200 rounded-lg p-6 mb-12">
            <h3 className="font-semibold text-gray-900 mb-3 flex items-center gap-2">
              <ExternalLink className="w-5 h-5 text-green-600" />
              Official Resources
            </h3>
            <ul className="space-y-2">
              <li>
                <a href="#" className="text-green-600 hover:text-green-700 flex items-center gap-2">
                  Central Pollution Control Board (CPCB) – EPR Guidelines
                  <ExternalLink className="w-4 h-4" />
                </a>
              </li>
              <li>
                <a href="#" className="text-green-600 hover:text-green-700 flex items-center gap-2">
                  Ministry of Environment, Forest and Climate Change (MoEFCC)
                  <ExternalLink className="w-4 h-4" />
                </a>
              </li>
            </ul>
          </div>

          {/* What is EPR */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-4 flex items-center gap-3">
              <FileText className="w-8 h-8 text-green-600" />
              What is Extended Producer Responsibility (EPR)?
            </h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              Extended Producer Responsibility (EPR) is a policy approach where manufacturers, importers, and brand 
              owners (PIBOs) are responsible for the entire lifecycle of their products, including post-consumer 
              waste management.
            </p>
            <p className="text-gray-700 leading-relaxed mb-4">
              This means companies must ensure that plastic waste, electronic waste, battery waste, and packaging 
              materials do not end up in landfills or pollute the environment. Instead, they must be collected, 
              recycled, or safely disposed of through authorized waste management systems.
            </p>
            <p className="text-gray-700 leading-relaxed">
              EPR is crucial in promoting a circular economy, reducing environmental damage, and encouraging 
              sustainable production and consumption practices.
            </p>
          </section>

          {/* EPR Rules */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">EPR Rules and Regulations in India</h2>
            <p className="text-gray-700 leading-relaxed mb-6">
              In India, EPR regulations are enforced by the Ministry of Environment, Forest and Climate Change 
              (MoEFCC) and the Central Pollution Control Board (CPCB). The key laws governing EPR compliance include:
            </p>

            <div className="space-y-6">
              {/* PWM Rules */}
              <div className="border-l-4 border-green-500 bg-gray-50 p-6 rounded-r-lg">
                <h3 className="font-bold text-xl text-gray-900 mb-3 flex items-center gap-2">
                  <Package className="w-6 h-6 text-green-600" />
                  Plastic Waste Management (PWM) Rules, 2016 (Amendments in 2022)
                </h3>
                <ul className="space-y-2 text-gray-700">
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">•</span>
                    <span>Mandates EPR compliance for producers, importers, and brand owners using plastic packaging.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">•</span>
                    <span>Requires businesses to recover and recycle a specified percentage of plastic waste.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-green-600 mt-1">•</span>
                    <span>Introduces the Plastic Credit Mechanism for businesses unable to meet direct recovery targets.</span>
                  </li>
                </ul>
              </div>

              {/* E-Waste Rules */}
              <div className="border-l-4 border-blue-500 bg-gray-50 p-6 rounded-r-lg">
                <h3 className="font-bold text-xl text-gray-900 mb-3 flex items-center gap-2">
                  <Zap className="w-6 h-6 text-blue-600" />
                  E-Waste (Management) Rules, 2022
                </h3>
                <ul className="space-y-2 text-gray-700">
                  <li className="flex items-start gap-2">
                    <span className="text-blue-600 mt-1">•</span>
                    <span>Applies to producers and importers of electronic and electrical equipment (EEE).</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-blue-600 mt-1">•</span>
                    <span>Companies must establish collection and recycling mechanisms for electronic waste.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-blue-600 mt-1">•</span>
                    <span>Mandates annual reporting of waste collected and processed.</span>
                  </li>
                </ul>
              </div>

              {/* Battery Rules */}
              <div className="border-l-4 border-yellow-500 bg-gray-50 p-6 rounded-r-lg">
                <h3 className="font-bold text-xl text-gray-900 mb-3 flex items-center gap-2">
                  <Battery className="w-6 h-6 text-yellow-600" />
                  Battery Waste Management Rules, 2022
                </h3>
                <ul className="space-y-2 text-gray-700">
                  <li className="flex items-start gap-2">
                    <span className="text-yellow-600 mt-1">•</span>
                    <span>Introduces EPR compliance for lead-acid, lithium-ion, and other battery manufacturers.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-yellow-600 mt-1">•</span>
                    <span>Requires businesses to establish battery recycling and safe disposal programs.</span>
                  </li>
                </ul>
              </div>

              {/* Hazardous Waste Rules */}
              <div className="border-l-4 border-red-500 bg-gray-50 p-6 rounded-r-lg">
                <h3 className="font-bold text-xl text-gray-900 mb-3 flex items-center gap-2">
                  <Factory className="w-6 h-6 text-red-600" />
                  Hazardous & Other Wastes Rules, 2016
                </h3>
                <ul className="space-y-2 text-gray-700">
                  <li className="flex items-start gap-2">
                    <span className="text-red-600 mt-1">•</span>
                    <span>Covers industries handling hazardous materials such as chemicals, medical waste, and other toxic substances.</span>
                  </li>
                  <li className="flex items-start gap-2">
                    <span className="text-red-600 mt-1">•</span>
                    <span>Mandates proper treatment and disposal to prevent environmental harm.</span>
                  </li>
                </ul>
              </div>
            </div>

            <div className="mt-6 bg-red-50 border border-red-200 rounded-lg p-4">
              <p className="text-red-800 font-semibold">
                ⚠️ Failure to comply with these EPR regulations can result in penalties, fines, and even business license revocation.
              </p>
            </div>
          </section>

          {/* Who Needs EPR */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">Who Needs EPR Registration in India?</h2>
            <p className="text-gray-700 leading-relaxed mb-6">
              EPR compliance applies to various businesses involved in the production, import, and sale of goods 
              that generate waste. If your company falls into any of the following categories, you are legally 
              required to register for EPR:
            </p>

            <div className="grid md:grid-cols-2 gap-4">
              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-6 h-6 text-green-600 flex-shrink-0 mt-1" />
                  <div>
                    <h4 className="font-semibold text-gray-900 mb-1">Producers & Manufacturers</h4>
                    <p className="text-sm text-gray-700">Companies that manufacture plastic packaging, electronic goods, or batteries.</p>
                  </div>
                </div>
              </div>

              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-6 h-6 text-green-600 flex-shrink-0 mt-1" />
                  <div>
                    <h4 className="font-semibold text-gray-900 mb-1">Importers</h4>
                    <p className="text-sm text-gray-700">Businesses importing plastic-packaged products, electronics, or batteries into India.</p>
                  </div>
                </div>
              </div>

              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-6 h-6 text-green-600 flex-shrink-0 mt-1" />
                  <div>
                    <h4 className="font-semibold text-gray-900 mb-1">Brand Owners</h4>
                    <p className="text-sm text-gray-700">Companies selling packaged goods, electronics, or products with plastic components.</p>
                  </div>
                </div>
              </div>

              <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-6 h-6 text-green-600 flex-shrink-0 mt-1" />
                  <div>
                    <h4 className="font-semibold text-gray-900 mb-1">Waste Processors</h4>
                    <p className="text-sm text-gray-700">Recycling and waste management companies handling waste collection, segregation, and disposal.</p>
                  </div>
                </div>
              </div>
            </div>

            <p className="text-gray-700 leading-relaxed mt-6 italic">
              If your company produces plastic waste, electronic waste, or battery waste, EPR registration is 
              mandatory under CPCB guidelines.
            </p>
          </section>

          {/* How to Get EPR Certification */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">How to Get EPR Certification in India?</h2>
            <p className="text-gray-700 leading-relaxed mb-6">
              To comply with EPR regulations, businesses must register, track, and report their waste management 
              efforts to the CPCB. Here's a step-by-step guide to obtaining EPR certification in India:
            </p>

            <div className="space-y-4">
              <div className="flex gap-4">
                <div className="flex-shrink-0 w-12 h-12 bg-green-600 text-white rounded-full flex items-center justify-center font-bold text-lg">
                  1
                </div>
                <div className="flex-1">
                  <h4 className="font-bold text-lg text-gray-900 mb-2">EPR Registration</h4>
                  <ul className="space-y-1 text-gray-700">
                    <li>• Apply for an EPR Authorization Certificate through the CPCB online portal.</li>
                    <li>• Submit business details, product categories, and estimated waste generation.</li>
                  </ul>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="flex-shrink-0 w-12 h-12 bg-green-600 text-white rounded-full flex items-center justify-center font-bold text-lg">
                  2
                </div>
                <div className="flex-1">
                  <h4 className="font-bold text-lg text-gray-900 mb-2">EPR Compliance Plan Submission</h4>
                  <ul className="space-y-1 text-gray-700">
                    <li>• Provide a detailed EPR Action Plan, outlining waste collection, recycling, and disposal mechanisms.</li>
                    <li>• Partner with authorized recyclers or third-party waste management agencies.</li>
                  </ul>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="flex-shrink-0 w-12 h-12 bg-green-600 text-white rounded-full flex items-center justify-center font-bold text-lg">
                  3
                </div>
                <div className="flex-1">
                  <h4 className="font-bold text-lg text-gray-900 mb-2">EPR Approval & Monitoring</h4>
                  <ul className="space-y-1 text-gray-700">
                    <li>• Once approved, businesses must implement their waste management plans as per CPCB regulations.</li>
                    <li>• Regular monitoring and audits ensure compliance.</li>
                  </ul>
                </div>
              </div>

              <div className="flex gap-4">
                <div className="flex-shrink-0 w-12 h-12 bg-green-600 text-white rounded-full flex items-center justify-center font-bold text-lg">
                  4
                </div>
                <div className="flex-1">
                  <h4 className="font-bold text-lg text-gray-900 mb-2">Annual EPR Reporting</h4>
                  <ul className="space-y-1 text-gray-700">
                    <li>• Companies must submit annual waste collection and recycling reports to the CPCB.</li>
                    <li>• Failure to meet targets can result in penalties or additional recovery obligations.</li>
                  </ul>
                </div>
              </div>
            </div>
          </section>

          {/* Benefits */}
          <section className="mb-12">
            <h2 className="text-3xl font-bold text-gray-900 mb-6">Benefits of EPR for Businesses</h2>
            <p className="text-gray-700 leading-relaxed mb-6">
              Complying with EPR regulations not only ensures legal compliance but also provides significant 
              business advantages:
            </p>

            <div className="space-y-3">
              <div className="flex items-start gap-3 bg-green-50 p-4 rounded-lg">
                <CheckCircle className="w-6 h-6 text-green-600 flex-shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-semibold text-gray-900">Regulatory Compliance</h4>
                  <p className="text-gray-700">Avoid penalties and legal issues by meeting government-mandated waste recovery targets.</p>
                </div>
              </div>

              <div className="flex items-start gap-3 bg-green-50 p-4 rounded-lg">
                <CheckCircle className="w-6 h-6 text-green-600 flex-shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-semibold text-gray-900">Sustainability Goals</h4>
                  <p className="text-gray-700">Contribute to India's circular economy and environmental conservation efforts.</p>
                </div>
              </div>

              <div className="flex items-start gap-3 bg-green-50 p-4 rounded-lg">
                <CheckCircle className="w-6 h-6 text-green-600 flex-shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-semibold text-gray-900">Corporate Social Responsibility (CSR)</h4>
                  <p className="text-gray-700">Enhance brand image by adopting eco-friendly business practices.</p>
                </div>
              </div>

              <div className="flex items-start gap-3 bg-green-50 p-4 rounded-lg">
                <CheckCircle className="w-6 h-6 text-green-600 flex-shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-semibold text-gray-900">Improved Consumer Trust</h4>
                  <p className="text-gray-700">Modern consumers prefer brands that demonstrate environmental responsibility.</p>
                </div>
              </div>

              <div className="flex items-start gap-3 bg-green-50 p-4 rounded-lg">
                <CheckCircle className="w-6 h-6 text-green-600 flex-shrink-0 mt-0.5" />
                <div>
                  <h4 className="font-semibold text-gray-900">Boosts Recycling & Waste Management</h4>
                  <p className="text-gray-700">Encourages investment in waste processing and recycling facilities.</p>
                </div>
              </div>
            </div>
          </section>

          {/* CTA Section */}
          <section className="bg-gradient-to-r from-green-600 to-emerald-600 rounded-xl p-8 text-white">
            <h2 className="text-3xl font-bold mb-4">Why Choose Us for EPR Compliance in India?</h2>
            <p className="text-green-50 mb-6">
              Navigating EPR regulations can be complex, but we simplify the process with:
            </p>

            <div className="grid md:grid-cols-2 gap-4 mb-6">
              <div className="bg-white/10 backdrop-blur rounded-lg p-4">
                <h4 className="font-semibold mb-2">Expert Guidance</h4>
                <p className="text-sm text-green-50">Assistance with documentation, registration, and compliance tracking.</p>
              </div>
              <div className="bg-white/10 backdrop-blur rounded-lg p-4">
                <h4 className="font-semibold mb-2">End-to-End Support</h4>
                <p className="text-sm text-green-50">From EPR certification to annual reporting, we handle everything.</p>
              </div>
              <div className="bg-white/10 backdrop-blur rounded-lg p-4">
                <h4 className="font-semibold mb-2">Industry-Specific Solutions</h4>
                <p className="text-sm text-green-50">Customized EPR strategies for businesses in plastic, electronics, and packaging sectors.</p>
              </div>
              <div className="bg-white/10 backdrop-blur rounded-lg p-4">
                <h4 className="font-semibold mb-2">Verified Waste Management Partners</h4>
                <p className="text-sm text-green-50">Connect with authorized recyclers and waste processors to fulfil EPR obligations.</p>
              </div>
            </div>

            {/* <button className="bg-white text-green-600 font-semibold px-8 py-3 rounded-lg hover:bg-green-50 transition-colors">
              Get Started with EPR Compliance
            </button> */}
          </section>
        </article>
      </main>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 py-8 mt-12">
        <div className="max-w-4xl mx-auto px-4 text-center">
          <p>© 2024 EPR Compliance India. All rights reserved.</p>
          <p className="text-sm mt-2">Helping businesses achieve environmental compliance and sustainability goals.</p>
        </div>
      </footer>
    </div>
  );
}